### ISSUE TITLE
Fragment OnclickListener

### ISSUE THREAD

**Issue by mayankshah1607** [mayankshah1607/noctis#3]
When the button 'fromdate' is clicked in the fragment 'MainActivityApply', nothing shows up

**Comment by yashvardhan-kukreja** [comment]
I checked the code. Apparently, there is no error and as you said nothing is happening when you click fromdate button. "dialog.show()", Add this line at the end of onClick function of 'fromdate' button. Actually, you are declaring the dialog but still the app doesn't know what to do with the dialog when the button is clicked. So, when the button clicked, the line "dialog.show()" tells the app to show the datepickerDialog. Just like we add .show() at the end of a Toast, it is something similar to this. I dont have the login credentials so I couldn't check the app but as far as I can see from the code, this must be the solution.
